import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "dist-capacitor/**",
      ".output/**",
      ".vinxi/**",
      "node_modules/**",
      "android/**",
      "ios/**",
      "coverage/**",
      // Generated by `supabase gen types typescript` (docs/authentication.md).
      // routeTree.gen.ts self-excludes via an inline `/* eslint-disable */`
      // banner; this file has no such banner, so it must be excluded here
      // instead. It alone accounted for 7,385 of the 7,391 lint errors
      // documented in docs/CI_LINT_DEBT.md — see
      // docs/sprint-2.2-developer-experience-ci-audit.md.
      "src/integrations/supabase/types.ts",
      // Emitted by the @lovable.dev/mcp-js Vite plugin (mcpPlugin(),
      // vite.config.ts) on every dev/build run — each carries its own
      // "AUTO-GENERATED ... Regenerated by the Vite plugin" banner.
      // Brackets are escaped: unescaped `[...]` is a glob character class.
      "src/routes/mcp.ts",
      "src/routes/\\[.mcp\\]/list-tools.ts",
      "src/routes/\\[.mcp\\]/invoke-tool/$tool.ts",
      "src/routes/\\[.well-known\\]/oauth-protected-resource.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,

      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],

      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],

      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
