/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors/index'
import { Route as AuthenticatedSalesOrdersIndexRouteImport } from './routes/_authenticated/sales-orders/index'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes/index'
import { Route as AuthenticatedPurchaseOrdersIndexRouteImport } from './routes/_authenticated/purchase-orders/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedFollowupsIndexRouteImport } from './routes/_authenticated/followups/index'
import { Route as AuthenticatedEnquiriesIndexRouteImport } from './routes/_authenticated/enquiries/index'
import { Route as AuthenticatedDispatchIndexRouteImport } from './routes/_authenticated/dispatch/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedSalesOrdersNewRouteImport } from './routes/_authenticated/sales-orders/new'
import { Route as AuthenticatedSalesOrdersIdRouteImport } from './routes/_authenticated/sales-orders/$id'
import { Route as AuthenticatedQuotesNewRouteImport } from './routes/_authenticated/quotes/new'
import { Route as AuthenticatedQuotesQuoteIdRouteImport } from './routes/_authenticated/quotes/$quoteId'
import { Route as AuthenticatedPurchaseOrdersNewRouteImport } from './routes/_authenticated/purchase-orders/new'
import { Route as AuthenticatedPurchaseOrdersIdRouteImport } from './routes/_authenticated/purchase-orders/$id'
import { Route as AuthenticatedPaymentsNewRouteImport } from './routes/_authenticated/payments/new'
import { Route as AuthenticatedPaymentsIdRouteImport } from './routes/_authenticated/payments/$id'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices/$invoiceId'
import { Route as AuthenticatedInventoryNewRouteImport } from './routes/_authenticated/inventory/new'
import { Route as AuthenticatedInventoryIdRouteImport } from './routes/_authenticated/inventory/$id'
import { Route as AuthenticatedEnquiriesEnquiryIdRouteImport } from './routes/_authenticated/enquiries/$enquiryId'
import { Route as AuthenticatedDispatchNewRouteImport } from './routes/_authenticated/dispatch/new'
import { Route as AuthenticatedDispatchIdRouteImport } from './routes/_authenticated/dispatch/$id'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'
import { Route as AuthenticatedSalesOrdersIdEditRouteImport } from './routes/_authenticated/sales-orders/$id.edit'
import { Route as AuthenticatedQuotesQuoteIdEditRouteImport } from './routes/_authenticated/quotes/$quoteId.edit'
import { Route as AuthenticatedPurchaseOrdersIdEditRouteImport } from './routes/_authenticated/purchase-orders/$id.edit'
import { Route as AuthenticatedPaymentsIdEditRouteImport } from './routes/_authenticated/payments/$id.edit'
import { Route as AuthenticatedInvoicesInvoiceIdEditRouteImport } from './routes/_authenticated/invoices/$invoiceId.edit'
import { Route as AuthenticatedInventoryIdEditRouteImport } from './routes/_authenticated/inventory/$id.edit'
import { Route as AuthenticatedDispatchIdEditRouteImport } from './routes/_authenticated/dispatch/$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersIndexRoute =
  AuthenticatedSalesOrdersIndexRouteImport.update({
    id: '/sales-orders/',
    path: '/sales-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIndexRoute =
  AuthenticatedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFollowupsIndexRoute =
  AuthenticatedFollowupsIndexRouteImport.update({
    id: '/followups/',
    path: '/followups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnquiriesIndexRoute =
  AuthenticatedEnquiriesIndexRouteImport.update({
    id: '/enquiries/',
    path: '/enquiries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDispatchIndexRoute =
  AuthenticatedDispatchIndexRouteImport.update({
    id: '/dispatch/',
    path: '/dispatch/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersNewRoute =
  AuthenticatedSalesOrdersNewRouteImport.update({
    id: '/sales-orders/new',
    path: '/sales-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersIdRoute =
  AuthenticatedSalesOrdersIdRouteImport.update({
    id: '/sales-orders/$id',
    path: '/sales-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesNewRoute = AuthenticatedQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesQuoteIdRoute =
  AuthenticatedQuotesQuoteIdRouteImport.update({
    id: '/quotes/$quoteId',
    path: '/quotes/$quoteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersNewRoute =
  AuthenticatedPurchaseOrdersNewRouteImport.update({
    id: '/purchase-orders/new',
    path: '/purchase-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdRoute =
  AuthenticatedPurchaseOrdersIdRouteImport.update({
    id: '/purchase-orders/$id',
    path: '/purchase-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsNewRoute =
  AuthenticatedPaymentsNewRouteImport.update({
    id: '/payments/new',
    path: '/payments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsIdRoute = AuthenticatedPaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryNewRoute =
  AuthenticatedInventoryNewRouteImport.update({
    id: '/inventory/new',
    path: '/inventory/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIdRoute =
  AuthenticatedInventoryIdRouteImport.update({
    id: '/inventory/$id',
    path: '/inventory/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnquiriesEnquiryIdRoute =
  AuthenticatedEnquiriesEnquiryIdRouteImport.update({
    id: '/enquiries/$enquiryId',
    path: '/enquiries/$enquiryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDispatchNewRoute =
  AuthenticatedDispatchNewRouteImport.update({
    id: '/dispatch/new',
    path: '/dispatch/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDispatchIdRoute = AuthenticatedDispatchIdRouteImport.update({
  id: '/dispatch/$id',
  path: '/dispatch/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSalesOrdersIdEditRoute =
  AuthenticatedSalesOrdersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSalesOrdersIdRoute,
  } as any)
const AuthenticatedQuotesQuoteIdEditRoute =
  AuthenticatedQuotesQuoteIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedQuotesQuoteIdRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdEditRoute =
  AuthenticatedPurchaseOrdersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPurchaseOrdersIdRoute,
  } as any)
const AuthenticatedPaymentsIdEditRoute =
  AuthenticatedPaymentsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPaymentsIdRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdEditRoute =
  AuthenticatedInvoicesInvoiceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedInvoicesInvoiceIdRoute,
  } as any)
const AuthenticatedInventoryIdEditRoute =
  AuthenticatedInventoryIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedInventoryIdRoute,
  } as any)
const AuthenticatedDispatchIdEditRoute =
  AuthenticatedDispatchIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedDispatchIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch/$id': typeof AuthenticatedDispatchIdRouteWithChildren
  '/dispatch/new': typeof AuthenticatedDispatchNewRoute
  '/enquiries/$enquiryId': typeof AuthenticatedEnquiriesEnquiryIdRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRouteWithChildren
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRouteWithChildren
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/payments/$id': typeof AuthenticatedPaymentsIdRouteWithChildren
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRouteWithChildren
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRouteWithChildren
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/sales-orders/$id': typeof AuthenticatedSalesOrdersIdRouteWithChildren
  '/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/dispatch/': typeof AuthenticatedDispatchIndexRoute
  '/enquiries/': typeof AuthenticatedEnquiriesIndexRoute
  '/followups/': typeof AuthenticatedFollowupsIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/sales-orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/dispatch/$id/edit': typeof AuthenticatedDispatchIdEditRoute
  '/inventory/$id/edit': typeof AuthenticatedInventoryIdEditRoute
  '/invoices/$invoiceId/edit': typeof AuthenticatedInvoicesInvoiceIdEditRoute
  '/payments/$id/edit': typeof AuthenticatedPaymentsIdEditRoute
  '/purchase-orders/$id/edit': typeof AuthenticatedPurchaseOrdersIdEditRoute
  '/quotes/$quoteId/edit': typeof AuthenticatedQuotesQuoteIdEditRoute
  '/sales-orders/$id/edit': typeof AuthenticatedSalesOrdersIdEditRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch/$id': typeof AuthenticatedDispatchIdRouteWithChildren
  '/dispatch/new': typeof AuthenticatedDispatchNewRoute
  '/enquiries/$enquiryId': typeof AuthenticatedEnquiriesEnquiryIdRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRouteWithChildren
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRouteWithChildren
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/payments/$id': typeof AuthenticatedPaymentsIdRouteWithChildren
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRouteWithChildren
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRouteWithChildren
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/sales-orders/$id': typeof AuthenticatedSalesOrdersIdRouteWithChildren
  '/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/dispatch': typeof AuthenticatedDispatchIndexRoute
  '/enquiries': typeof AuthenticatedEnquiriesIndexRoute
  '/followups': typeof AuthenticatedFollowupsIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/sales-orders': typeof AuthenticatedSalesOrdersIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/dispatch/$id/edit': typeof AuthenticatedDispatchIdEditRoute
  '/inventory/$id/edit': typeof AuthenticatedInventoryIdEditRoute
  '/invoices/$invoiceId/edit': typeof AuthenticatedInvoicesInvoiceIdEditRoute
  '/payments/$id/edit': typeof AuthenticatedPaymentsIdEditRoute
  '/purchase-orders/$id/edit': typeof AuthenticatedPurchaseOrdersIdEditRoute
  '/quotes/$quoteId/edit': typeof AuthenticatedQuotesQuoteIdEditRoute
  '/sales-orders/$id/edit': typeof AuthenticatedSalesOrdersIdEditRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispatch/$id': typeof AuthenticatedDispatchIdRouteWithChildren
  '/_authenticated/dispatch/new': typeof AuthenticatedDispatchNewRoute
  '/_authenticated/enquiries/$enquiryId': typeof AuthenticatedEnquiriesEnquiryIdRoute
  '/_authenticated/inventory/$id': typeof AuthenticatedInventoryIdRouteWithChildren
  '/_authenticated/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRouteWithChildren
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/payments/$id': typeof AuthenticatedPaymentsIdRouteWithChildren
  '/_authenticated/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/_authenticated/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRouteWithChildren
  '/_authenticated/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/_authenticated/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRouteWithChildren
  '/_authenticated/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/_authenticated/sales-orders/$id': typeof AuthenticatedSalesOrdersIdRouteWithChildren
  '/_authenticated/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/dispatch/': typeof AuthenticatedDispatchIndexRoute
  '/_authenticated/enquiries/': typeof AuthenticatedEnquiriesIndexRoute
  '/_authenticated/followups/': typeof AuthenticatedFollowupsIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/_authenticated/sales-orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/dispatch/$id/edit': typeof AuthenticatedDispatchIdEditRoute
  '/_authenticated/inventory/$id/edit': typeof AuthenticatedInventoryIdEditRoute
  '/_authenticated/invoices/$invoiceId/edit': typeof AuthenticatedInvoicesInvoiceIdEditRoute
  '/_authenticated/payments/$id/edit': typeof AuthenticatedPaymentsIdEditRoute
  '/_authenticated/purchase-orders/$id/edit': typeof AuthenticatedPurchaseOrdersIdEditRoute
  '/_authenticated/quotes/$quoteId/edit': typeof AuthenticatedQuotesQuoteIdEditRoute
  '/_authenticated/sales-orders/$id/edit': typeof AuthenticatedSalesOrdersIdEditRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dispatch/$id'
    | '/dispatch/new'
    | '/enquiries/$enquiryId'
    | '/inventory/$id'
    | '/inventory/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/payments/$id'
    | '/payments/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/sales-orders/$id'
    | '/sales-orders/new'
    | '/customers/'
    | '/dispatch/'
    | '/enquiries/'
    | '/followups/'
    | '/inventory/'
    | '/invoices/'
    | '/payments/'
    | '/products/'
    | '/projects/'
    | '/purchase-orders/'
    | '/quotes/'
    | '/sales-orders/'
    | '/vendors/'
    | '/dispatch/$id/edit'
    | '/inventory/$id/edit'
    | '/invoices/$invoiceId/edit'
    | '/payments/$id/edit'
    | '/purchase-orders/$id/edit'
    | '/quotes/$quoteId/edit'
    | '/sales-orders/$id/edit'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dispatch/$id'
    | '/dispatch/new'
    | '/enquiries/$enquiryId'
    | '/inventory/$id'
    | '/inventory/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/payments/$id'
    | '/payments/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/sales-orders/$id'
    | '/sales-orders/new'
    | '/customers'
    | '/dispatch'
    | '/enquiries'
    | '/followups'
    | '/inventory'
    | '/invoices'
    | '/payments'
    | '/products'
    | '/projects'
    | '/purchase-orders'
    | '/quotes'
    | '/sales-orders'
    | '/vendors'
    | '/dispatch/$id/edit'
    | '/inventory/$id/edit'
    | '/invoices/$invoiceId/edit'
    | '/payments/$id/edit'
    | '/purchase-orders/$id/edit'
    | '/quotes/$quoteId/edit'
    | '/sales-orders/$id/edit'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispatch/$id'
    | '/_authenticated/dispatch/new'
    | '/_authenticated/enquiries/$enquiryId'
    | '/_authenticated/inventory/$id'
    | '/_authenticated/inventory/new'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/invoices/new'
    | '/_authenticated/payments/$id'
    | '/_authenticated/payments/new'
    | '/_authenticated/purchase-orders/$id'
    | '/_authenticated/purchase-orders/new'
    | '/_authenticated/quotes/$quoteId'
    | '/_authenticated/quotes/new'
    | '/_authenticated/sales-orders/$id'
    | '/_authenticated/sales-orders/new'
    | '/_authenticated/customers/'
    | '/_authenticated/dispatch/'
    | '/_authenticated/enquiries/'
    | '/_authenticated/followups/'
    | '/_authenticated/inventory/'
    | '/_authenticated/invoices/'
    | '/_authenticated/payments/'
    | '/_authenticated/products/'
    | '/_authenticated/projects/'
    | '/_authenticated/purchase-orders/'
    | '/_authenticated/quotes/'
    | '/_authenticated/sales-orders/'
    | '/_authenticated/vendors/'
    | '/_authenticated/dispatch/$id/edit'
    | '/_authenticated/inventory/$id/edit'
    | '/_authenticated/invoices/$invoiceId/edit'
    | '/_authenticated/payments/$id/edit'
    | '/_authenticated/purchase-orders/$id/edit'
    | '/_authenticated/quotes/$quoteId/edit'
    | '/_authenticated/sales-orders/$id/edit'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders/': {
      id: '/_authenticated/sales-orders/'
      path: '/sales-orders'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/': {
      id: '/_authenticated/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups/': {
      id: '/_authenticated/followups/'
      path: '/followups'
      fullPath: '/followups/'
      preLoaderRoute: typeof AuthenticatedFollowupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquiries/': {
      id: '/_authenticated/enquiries/'
      path: '/enquiries'
      fullPath: '/enquiries/'
      preLoaderRoute: typeof AuthenticatedEnquiriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch/': {
      id: '/_authenticated/dispatch/'
      path: '/dispatch'
      fullPath: '/dispatch/'
      preLoaderRoute: typeof AuthenticatedDispatchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders/new': {
      id: '/_authenticated/sales-orders/new'
      path: '/sales-orders/new'
      fullPath: '/sales-orders/new'
      preLoaderRoute: typeof AuthenticatedSalesOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders/$id': {
      id: '/_authenticated/sales-orders/$id'
      path: '/sales-orders/$id'
      fullPath: '/sales-orders/$id'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/new': {
      id: '/_authenticated/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedQuotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/$quoteId': {
      id: '/_authenticated/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AuthenticatedQuotesQuoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/new': {
      id: '/_authenticated/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/$id': {
      id: '/_authenticated/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/new': {
      id: '/_authenticated/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof AuthenticatedPaymentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/$id': {
      id: '/_authenticated/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof AuthenticatedPaymentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/new': {
      id: '/_authenticated/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AuthenticatedInventoryNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/$id': {
      id: '/_authenticated/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AuthenticatedInventoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquiries/$enquiryId': {
      id: '/_authenticated/enquiries/$enquiryId'
      path: '/enquiries/$enquiryId'
      fullPath: '/enquiries/$enquiryId'
      preLoaderRoute: typeof AuthenticatedEnquiriesEnquiryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch/new': {
      id: '/_authenticated/dispatch/new'
      path: '/dispatch/new'
      fullPath: '/dispatch/new'
      preLoaderRoute: typeof AuthenticatedDispatchNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch/$id': {
      id: '/_authenticated/dispatch/$id'
      path: '/dispatch/$id'
      fullPath: '/dispatch/$id'
      preLoaderRoute: typeof AuthenticatedDispatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales-orders/$id/edit': {
      id: '/_authenticated/sales-orders/$id/edit'
      path: '/edit'
      fullPath: '/sales-orders/$id/edit'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIdEditRouteImport
      parentRoute: typeof AuthenticatedSalesOrdersIdRoute
    }
    '/_authenticated/quotes/$quoteId/edit': {
      id: '/_authenticated/quotes/$quoteId/edit'
      path: '/edit'
      fullPath: '/quotes/$quoteId/edit'
      preLoaderRoute: typeof AuthenticatedQuotesQuoteIdEditRouteImport
      parentRoute: typeof AuthenticatedQuotesQuoteIdRoute
    }
    '/_authenticated/purchase-orders/$id/edit': {
      id: '/_authenticated/purchase-orders/$id/edit'
      path: '/edit'
      fullPath: '/purchase-orders/$id/edit'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdEditRouteImport
      parentRoute: typeof AuthenticatedPurchaseOrdersIdRoute
    }
    '/_authenticated/payments/$id/edit': {
      id: '/_authenticated/payments/$id/edit'
      path: '/edit'
      fullPath: '/payments/$id/edit'
      preLoaderRoute: typeof AuthenticatedPaymentsIdEditRouteImport
      parentRoute: typeof AuthenticatedPaymentsIdRoute
    }
    '/_authenticated/invoices/$invoiceId/edit': {
      id: '/_authenticated/invoices/$invoiceId/edit'
      path: '/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
    }
    '/_authenticated/inventory/$id/edit': {
      id: '/_authenticated/inventory/$id/edit'
      path: '/edit'
      fullPath: '/inventory/$id/edit'
      preLoaderRoute: typeof AuthenticatedInventoryIdEditRouteImport
      parentRoute: typeof AuthenticatedInventoryIdRoute
    }
    '/_authenticated/dispatch/$id/edit': {
      id: '/_authenticated/dispatch/$id/edit'
      path: '/edit'
      fullPath: '/dispatch/$id/edit'
      preLoaderRoute: typeof AuthenticatedDispatchIdEditRouteImport
      parentRoute: typeof AuthenticatedDispatchIdRoute
    }
  }
}

interface AuthenticatedDispatchIdRouteChildren {
  AuthenticatedDispatchIdEditRoute: typeof AuthenticatedDispatchIdEditRoute
}

const AuthenticatedDispatchIdRouteChildren: AuthenticatedDispatchIdRouteChildren =
  {
    AuthenticatedDispatchIdEditRoute: AuthenticatedDispatchIdEditRoute,
  }

const AuthenticatedDispatchIdRouteWithChildren =
  AuthenticatedDispatchIdRoute._addFileChildren(
    AuthenticatedDispatchIdRouteChildren,
  )

interface AuthenticatedInventoryIdRouteChildren {
  AuthenticatedInventoryIdEditRoute: typeof AuthenticatedInventoryIdEditRoute
}

const AuthenticatedInventoryIdRouteChildren: AuthenticatedInventoryIdRouteChildren =
  {
    AuthenticatedInventoryIdEditRoute: AuthenticatedInventoryIdEditRoute,
  }

const AuthenticatedInventoryIdRouteWithChildren =
  AuthenticatedInventoryIdRoute._addFileChildren(
    AuthenticatedInventoryIdRouteChildren,
  )

interface AuthenticatedInvoicesInvoiceIdRouteChildren {
  AuthenticatedInvoicesInvoiceIdEditRoute: typeof AuthenticatedInvoicesInvoiceIdEditRoute
}

const AuthenticatedInvoicesInvoiceIdRouteChildren: AuthenticatedInvoicesInvoiceIdRouteChildren =
  {
    AuthenticatedInvoicesInvoiceIdEditRoute:
      AuthenticatedInvoicesInvoiceIdEditRoute,
  }

const AuthenticatedInvoicesInvoiceIdRouteWithChildren =
  AuthenticatedInvoicesInvoiceIdRoute._addFileChildren(
    AuthenticatedInvoicesInvoiceIdRouteChildren,
  )

interface AuthenticatedPaymentsIdRouteChildren {
  AuthenticatedPaymentsIdEditRoute: typeof AuthenticatedPaymentsIdEditRoute
}

const AuthenticatedPaymentsIdRouteChildren: AuthenticatedPaymentsIdRouteChildren =
  {
    AuthenticatedPaymentsIdEditRoute: AuthenticatedPaymentsIdEditRoute,
  }

const AuthenticatedPaymentsIdRouteWithChildren =
  AuthenticatedPaymentsIdRoute._addFileChildren(
    AuthenticatedPaymentsIdRouteChildren,
  )

interface AuthenticatedPurchaseOrdersIdRouteChildren {
  AuthenticatedPurchaseOrdersIdEditRoute: typeof AuthenticatedPurchaseOrdersIdEditRoute
}

const AuthenticatedPurchaseOrdersIdRouteChildren: AuthenticatedPurchaseOrdersIdRouteChildren =
  {
    AuthenticatedPurchaseOrdersIdEditRoute:
      AuthenticatedPurchaseOrdersIdEditRoute,
  }

const AuthenticatedPurchaseOrdersIdRouteWithChildren =
  AuthenticatedPurchaseOrdersIdRoute._addFileChildren(
    AuthenticatedPurchaseOrdersIdRouteChildren,
  )

interface AuthenticatedQuotesQuoteIdRouteChildren {
  AuthenticatedQuotesQuoteIdEditRoute: typeof AuthenticatedQuotesQuoteIdEditRoute
}

const AuthenticatedQuotesQuoteIdRouteChildren: AuthenticatedQuotesQuoteIdRouteChildren =
  {
    AuthenticatedQuotesQuoteIdEditRoute: AuthenticatedQuotesQuoteIdEditRoute,
  }

const AuthenticatedQuotesQuoteIdRouteWithChildren =
  AuthenticatedQuotesQuoteIdRoute._addFileChildren(
    AuthenticatedQuotesQuoteIdRouteChildren,
  )

interface AuthenticatedSalesOrdersIdRouteChildren {
  AuthenticatedSalesOrdersIdEditRoute: typeof AuthenticatedSalesOrdersIdEditRoute
}

const AuthenticatedSalesOrdersIdRouteChildren: AuthenticatedSalesOrdersIdRouteChildren =
  {
    AuthenticatedSalesOrdersIdEditRoute: AuthenticatedSalesOrdersIdEditRoute,
  }

const AuthenticatedSalesOrdersIdRouteWithChildren =
  AuthenticatedSalesOrdersIdRoute._addFileChildren(
    AuthenticatedSalesOrdersIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispatchIdRoute: typeof AuthenticatedDispatchIdRouteWithChildren
  AuthenticatedDispatchNewRoute: typeof AuthenticatedDispatchNewRoute
  AuthenticatedEnquiriesEnquiryIdRoute: typeof AuthenticatedEnquiriesEnquiryIdRoute
  AuthenticatedInventoryIdRoute: typeof AuthenticatedInventoryIdRouteWithChildren
  AuthenticatedInventoryNewRoute: typeof AuthenticatedInventoryNewRoute
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRouteWithChildren
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedPaymentsIdRoute: typeof AuthenticatedPaymentsIdRouteWithChildren
  AuthenticatedPaymentsNewRoute: typeof AuthenticatedPaymentsNewRoute
  AuthenticatedPurchaseOrdersIdRoute: typeof AuthenticatedPurchaseOrdersIdRouteWithChildren
  AuthenticatedPurchaseOrdersNewRoute: typeof AuthenticatedPurchaseOrdersNewRoute
  AuthenticatedQuotesQuoteIdRoute: typeof AuthenticatedQuotesQuoteIdRouteWithChildren
  AuthenticatedQuotesNewRoute: typeof AuthenticatedQuotesNewRoute
  AuthenticatedSalesOrdersIdRoute: typeof AuthenticatedSalesOrdersIdRouteWithChildren
  AuthenticatedSalesOrdersNewRoute: typeof AuthenticatedSalesOrdersNewRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDispatchIndexRoute: typeof AuthenticatedDispatchIndexRoute
  AuthenticatedEnquiriesIndexRoute: typeof AuthenticatedEnquiriesIndexRoute
  AuthenticatedFollowupsIndexRoute: typeof AuthenticatedFollowupsIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedPurchaseOrdersIndexRoute: typeof AuthenticatedPurchaseOrdersIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
  AuthenticatedSalesOrdersIndexRoute: typeof AuthenticatedSalesOrdersIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispatchIdRoute: AuthenticatedDispatchIdRouteWithChildren,
  AuthenticatedDispatchNewRoute: AuthenticatedDispatchNewRoute,
  AuthenticatedEnquiriesEnquiryIdRoute: AuthenticatedEnquiriesEnquiryIdRoute,
  AuthenticatedInventoryIdRoute: AuthenticatedInventoryIdRouteWithChildren,
  AuthenticatedInventoryNewRoute: AuthenticatedInventoryNewRoute,
  AuthenticatedInvoicesInvoiceIdRoute:
    AuthenticatedInvoicesInvoiceIdRouteWithChildren,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedPaymentsIdRoute: AuthenticatedPaymentsIdRouteWithChildren,
  AuthenticatedPaymentsNewRoute: AuthenticatedPaymentsNewRoute,
  AuthenticatedPurchaseOrdersIdRoute:
    AuthenticatedPurchaseOrdersIdRouteWithChildren,
  AuthenticatedPurchaseOrdersNewRoute: AuthenticatedPurchaseOrdersNewRoute,
  AuthenticatedQuotesQuoteIdRoute: AuthenticatedQuotesQuoteIdRouteWithChildren,
  AuthenticatedQuotesNewRoute: AuthenticatedQuotesNewRoute,
  AuthenticatedSalesOrdersIdRoute: AuthenticatedSalesOrdersIdRouteWithChildren,
  AuthenticatedSalesOrdersNewRoute: AuthenticatedSalesOrdersNewRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDispatchIndexRoute: AuthenticatedDispatchIndexRoute,
  AuthenticatedEnquiriesIndexRoute: AuthenticatedEnquiriesIndexRoute,
  AuthenticatedFollowupsIndexRoute: AuthenticatedFollowupsIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedPurchaseOrdersIndexRoute: AuthenticatedPurchaseOrdersIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
  AuthenticatedSalesOrdersIndexRoute: AuthenticatedSalesOrdersIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
