-- Phase G.9A.1 -- Document numbering cleanup.
--
-- Root cause (investigated, not a code/logic bug): every document number in
-- this schema is generated by the existing `entity_sequences` table +
-- `next_code(prefix)` function (see 20260630231639_...sql), a single shared
-- counter per prefix incremented atomically on INSERT via BEFORE INSERT
-- triggers (assign_customer_code, assign_enquiry_code, assign_quote_code,
-- assign_so_code, assign_invoice_code, assign_payment_code,
-- assign_receipt_code). That mechanism is correct and is NOT changed here.
-- The visible gap (e.g. customers starting at CUS-000061) is purely a
-- byproduct of demo data having been seeded across many separate migrations
-- over time, all drawing from the same counter.
--
-- This migration renumbers the seven document types named in the phase
-- spec -- customers, enquiries, quotes, sales_orders, invoices, payments,
-- receipts -- sequentially from 000001, ordered by creation order, and reset
-- each prefix's `entity_sequences.last_value` so every future INSERT
-- continues correctly from the new count. Every real relation elsewhere in
-- the schema (quote_id, customer_id, invoice_id, ...) is a UUID foreign key,
-- never the human-readable code string, so no other table needs updating --
-- confirmed by inspecting every reference to these columns across the
-- migration history: reconciliation/ledger views select invoice_no/
-- receipt_no/payment_no live from the base tables, so they pick up the new
-- values automatically on next read.
--
-- Each table is renumbered in two phases to guarantee no UNIQUE constraint
-- collision mid-update (new compact numbers can otherwise collide with a
-- not-yet-renumbered row's current number): first every row gets a
-- guaranteed-unique placeholder, then every row gets its final sequential
-- code. Renumbering only touches the *_code/*_no columns themselves --
-- historical free-text snapshots elsewhere (e.g. the JSONB audit payload
-- written by the customer-reassignment/ownership-transfer RPCs, which
-- captures customer_code as a point-in-time value) are intentionally left
-- untouched; they are historical records of what was true at that moment,
-- not live lookups.
--
-- receipts.receipt_no's width is also bumped from 5 to 6 digits (RCT-000001
-- instead of RCT-00001) to match the uniform 6-digit width every other
-- document type in this phase uses.

DO $$
DECLARE
  v_count bigint;
BEGIN
  -- ---------------------------------------------------------------------
  -- Customers (CUS)
  -- ---------------------------------------------------------------------
  UPDATE public.customers SET customer_code = 'TMP-RENUM-' || id::text;
  WITH ranked AS (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM public.customers
  )
  UPDATE public.customers c SET customer_code = 'CUS-' || lpad(ranked.rn::text, 6, '0')
  FROM ranked WHERE c.id = ranked.id;
  SELECT count(*) INTO v_count FROM public.customers;
  UPDATE public.entity_sequences SET last_value = v_count WHERE prefix = 'CUS';

  -- ---------------------------------------------------------------------
  -- Enquiries (ENQ)
  -- ---------------------------------------------------------------------
  UPDATE public.enquiries SET enquiry_no = 'TMP-RENUM-' || id::text;
  WITH ranked AS (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM public.enquiries
  )
  UPDATE public.enquiries e SET enquiry_no = 'ENQ-' || lpad(ranked.rn::text, 6, '0')
  FROM ranked WHERE e.id = ranked.id;
  SELECT count(*) INTO v_count FROM public.enquiries;
  UPDATE public.entity_sequences SET last_value = v_count WHERE prefix = 'ENQ';

  -- ---------------------------------------------------------------------
  -- Quotations (QUO)
  -- ---------------------------------------------------------------------
  UPDATE public.quotes SET quote_no = 'TMP-RENUM-' || id::text;
  WITH ranked AS (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM public.quotes
  )
  UPDATE public.quotes q SET quote_no = 'QUO-' || lpad(ranked.rn::text, 6, '0')
  FROM ranked WHERE q.id = ranked.id;
  SELECT count(*) INTO v_count FROM public.quotes;
  UPDATE public.entity_sequences SET last_value = v_count WHERE prefix = 'QUO';

  -- ---------------------------------------------------------------------
  -- Sales Orders (SO)
  -- ---------------------------------------------------------------------
  UPDATE public.sales_orders SET so_no = 'TMP-RENUM-' || id::text;
  WITH ranked AS (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM public.sales_orders
  )
  UPDATE public.sales_orders s SET so_no = 'SO-' || lpad(ranked.rn::text, 6, '0')
  FROM ranked WHERE s.id = ranked.id;
  SELECT count(*) INTO v_count FROM public.sales_orders;
  UPDATE public.entity_sequences SET last_value = v_count WHERE prefix = 'SO';

  -- ---------------------------------------------------------------------
  -- Invoices (INV)
  -- ---------------------------------------------------------------------
  UPDATE public.invoices SET invoice_no = 'TMP-RENUM-' || id::text;
  WITH ranked AS (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM public.invoices
  )
  UPDATE public.invoices i SET invoice_no = 'INV-' || lpad(ranked.rn::text, 6, '0')
  FROM ranked WHERE i.id = ranked.id;
  SELECT count(*) INTO v_count FROM public.invoices;
  UPDATE public.entity_sequences SET last_value = v_count WHERE prefix = 'INV';

  -- ---------------------------------------------------------------------
  -- Payments (PAY)
  -- ---------------------------------------------------------------------
  UPDATE public.payments SET payment_no = 'TMP-RENUM-' || id::text;
  WITH ranked AS (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM public.payments
  )
  UPDATE public.payments p SET payment_no = 'PAY-' || lpad(ranked.rn::text, 6, '0')
  FROM ranked WHERE p.id = ranked.id;
  SELECT count(*) INTO v_count FROM public.payments;
  UPDATE public.entity_sequences SET last_value = v_count WHERE prefix = 'PAY';

  -- ---------------------------------------------------------------------
  -- Receipts (RCT) -- also bump width 5 -> 6 to match the other prefixes.
  -- ---------------------------------------------------------------------
  UPDATE public.receipts SET receipt_no = 'TMP-RENUM-' || id::text;
  WITH ranked AS (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM public.receipts
  )
  UPDATE public.receipts r SET receipt_no = 'RCT-' || lpad(ranked.rn::text, 6, '0')
  FROM ranked WHERE r.id = ranked.id;
  SELECT count(*) INTO v_count FROM public.receipts;
  UPDATE public.entity_sequences SET last_value = v_count, width = 6 WHERE prefix = 'RCT';
END $$;
