
ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS place_of_supply TEXT,
  ADD COLUMN IF NOT EXISTS reverse_charge BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE public.invoice_items
  ADD COLUMN IF NOT EXISTS hsn_sac TEXT,
  ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(14,2);

ALTER TABLE public.sales_order_items
  ADD COLUMN IF NOT EXISTS hsn_sac TEXT,
  ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(14,2);

ALTER TABLE public.quote_items
  ADD COLUMN IF NOT EXISTS hsn_sac TEXT,
  ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(14,2);

ALTER TABLE public.estimate_items
  ADD COLUMN IF NOT EXISTS hsn_sac TEXT,
  ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(14,2);
